### ISSUE TITLE
这里的部署流程链接并不能点击进去

### ISSUE THREAD

**Issue by OrchardRX** [jason-wj/uniswap-v2#1]
uniswap的过程分析和部署过程讲解的链接点进入没有看到内容，能解决一下？我想看一下您给的详解决

**Comment by bitxx** [comment]
> uniswap的过程分析和部署过程讲解的链接点进入没有看到内容，能解决一下？我想看一下您给的详解决

README.md中的链接问题已修复

**Comment by bitxx** [comment]
closed
